### ISSUE TITLE
Classloader support

### ISSUE THREAD

**Issue by rsoti** [offbynull/coroutines#50]
Would it be possible to provide a specific ClassLoader implementation to instrument classes runtime similarly to javaflow? This way coroutines could be used nicely in Eclipse (Eclipse has an own compiler).

**Comment by offbynull** [comment]
I think this may be doable. By providing a new ClassInformationRepository implementation that queries a ClassLoader when ClassInformationRepository.getInformation(), things should hopefully "just work"... hopefully.

Can you provide more information on your use-case? How will providing this new mechanic support developers using Eclipse? Are you attempting to write an Eclipse plugin?

**Comment by rsoti** [comment]
The ClassLoader based ClassInformationRepository implementation sounds perfectly.
About my usecase:
We have javaflow continuation in our application, but decided to replace the continuation framework as the current one has no java 8 support. We use maven plugin to build the application (so your maven plugin would be fine to instrument our classes). But during the development maven task is inconvenient (Eclipse's compiler works on the fly and it is super fast). To use continuation the classes still need to be instrumented. Therefore we have a special Main classs starting the application in Eclipse, which uses javaflow's ContinuationClassLoader. We start the application this way:

    final ContinuationClassLoader cl = new ContinuationClassLoader(
					new URL[]{},
					Thread.currentThread().getContextClassLoader()); // chain parent class loader

			// Add default package root to override class loader for this package and its subpackages.
			cl.addLoaderPackageRoot(DEFAULT_ROOT);

			// start a new thread with a replaced classloader, this way the new class loader will be in use
			final Thread t = new Thread((Runnable)cl.forceLoadClass(runnable.getClass().getCanonicalName()).newInstance());
			t.setContextClassLoader(cl);
			t.start();

			// wait for the new thread to exit
			t.join();

The continuation classloader instruments our classes at runtime and this trick works in Eclipse and we don't need a new Eclipse plugin for that. Furthermore this is an IDE indenpendent solution.

**Comment by offbynull** [comment]
Apologies for the delay.

Haven't had a chance to look in to this yet. It may be a couple of weeks before I get to it.

**Comment by offbynull** [comment]
Okay, so I did a quick-and-dirty change to Javaflow's ContinuationClassLoader such that it uses Coroutine's instrumenter instead of Javaflow. There were very few changes involved (less than 10 lines). You can find the code here...

https://gist.github.com/offbynull/fcdbadbfe07360d507b1

Unfortunately this can't be included in Coroutines for a couple of reasons

1) Licensing incompatibilities.

2) It derives class information via the "java.class.path" system property rather than deriving class information from a classloader (as I mentioned in my previous comments). Deriving class information from a classloader requires abstracting out ClassInformationRepository, which won't be happening until Java 9's release.

Hopefully the ContinuationClassLoader implementation linked to above will do what you need. However, I think a better approach would be to use maven through eclipse.

**Comment by offbynull** [comment]
Okay so I abstracted out ClassInformationRepository. There's now a ClassloaderClassInformationRepository, but like I mentioned it will be a while before it gets released.

You can use it now if you'd like, but you'll have to clone the repo and build the source yourself. If you choose to do that, you can make use of the new ClassloaderClassInformationRepository by swapping out the constructor in the modified ContinuationClassLoader with the following...

```java
    public ContinuationClassLoader(URL[] urls, ClassLoader parent) throws IOException {
        super(urls,fixNullParent(parent));
        ClassLoaderClassInformationRepository repo = new ClassLoaderClassInformationRepository(parent);
        this.instrumenter = new Instrumenter(repo);
        acc = AccessController.getContext();
    }
```

**Comment by offbynull** [comment]
Closing this ticket EOD today.

**Comment by rsoti** [comment]
Sounds good. Thank you!
