### ISSUE TITLE
How can i get started in intellij idea?

### ISSUE THREAD

**Issue by 122274659** [offbynull/coroutines#54]
Hello, when i import your dependency in pom.xml, and create MyCoroutine.java just like readme said, but it seems didin't work. And the Console shows:
started
Exception in thread "main" com.offbynull.coroutines.user.CoroutineException: Exception thrown during execution
0
	at com.offbynull.coroutines.user.CoroutineRunner.execute(CoroutineRunner.java:59)
	at MyCoroutine.main(MyCoroutine.java:24)
Caused by: java.lang.UnsupportedOperationException: Caller not instrumented
	at com.offbynull.coroutines.user.Continuation.suspend(Continuation.java:179)
	at MyCoroutine.echo(MyCoroutine.java:19)
	at MyCoroutine.run(MyCoroutine.java:13)
	at com.offbynull.coroutines.user.CoroutineRunner.execute(CoroutineRunner.java:56)
	... 1 more

is there some operation wrong or left ?Or can u give me more details about how to start up this project?

**Comment by offbynull** [comment]
Hey,

IntelliJ (like NetBeans) tries to do its own thing instead of delegating to Maven. If you want to use Maven directly, here's how you set up your project...

1. Go to Run -> Edit Configurations
2. Add an "Application"
3. Type in your Main class
4. In the "Before launch" section, remove "Make" and add in "Run Maven Goal" with command-line set to "clean install"

You'll need to do something similar for running your unit tests, etc.., etc...

Here's a picture: http://imgur.com/PQtOHMT

I'm going to begin work on optimizing the maven plugin/instrumenter so that it isn't so slow (hopefully in the next couple of months).

**Comment by offbynull** [comment]
If this answers your question, please close the ticket.

**Comment by 122274659** [comment]
Really appreciate  your replay, it really works~
Now i am going to study its implementation, but the program excution order is quite different with other java program, so do u have some advise about how to understand your designation as soon as possible?Or could u give me some tips what  technique shold i learn before i can undertand your implementation?

**Comment by offbynull** [comment]
It's a little tough to explain because you have to know how the JVM works / how Java bytecode was designed. Here's a simple explanation...

The instrumenter looks for methods that take in a **Continuation** object and modifies them. The modifications involve adding "loading" code at the beginning of the method and "saving" code whenever a method that takes in a Continuation object is invoked or Continuation.suspend() is invoked.

The way Java bytecode was designed... at any point in the code, you know at **design-time** how many items are on the stack and what types those items are.

So, for example, let's say suspend() gets called at instruction 17. At instruction 17, we know how large the stack is and the types of items in the stack (e.g. int, String, Object, ...). When the instrumenter sees a call to suspend(), it removes suspend() and replaces it with instructions to pop and save each item off the stack, save the location at which suspend() was called (e.g. this is the 2nd suspend in the method), and then returns from the method.

The code will keep saving and returning for each method in the call stack as it works its way up and out of the coroutine.

When you continue your coroutine, the "loading" code will read the saved information in each method and re-create the call stack + stack.


The implementation is a bit more complicated than described because there are optimizations and a lot of extra conditions/cases to worry about. I would encourage you to go through the code -- you can start by going to com.offbynull.coroutines.instrumenter.Instrumenter class. There are are a lot of comments sprinkled throughout the code to help explain things / make things easier to read.
