### ISSUE TITLE
Can't run the example code

### ISSUE THREAD

**Issue by fattyhan** [offbynull/coroutines#78]
There will throws a Exception when run the Continuation.suspend(); ,and the main method exit.

`public  final class MyCoroutine implements Coroutine {

    private void echo(Continuation c, int x) {
        System.out.println(x);
        c.suspend();
    }

    public static void main(String[] args) {
        CoroutineRunner r = new CoroutineRunner(new MyCoroutine());
        try {
            r.execute();
            r.execute();
            r.execute();
            r.execute();
        }catch (final Exception e){
            r.execute();
        }finally {
            r.execute();
        }
    }

    @Override
    public void run(Continuation c) throws Exception {
            System.out.println("started");
            for (int i = 0; i < 10; i++) {
                echo(c, i);
        }
    }
}`

**Comment by offbynull** [comment]
Did you instrument your code? What's the exception?

**Comment by fattyhan** [comment]
@offbynull 
`  /**
     * Call to suspend/yield execution.
     * @throws UnsupportedOperationException if the caller has not been instrumented
     */
    public void suspend() {
        throw new UnsupportedOperationException("Caller not instrumented");
    }`

**Comment by offbynull** [comment]
You need to instrument your coroutines. Read the readme.

**Comment by fattyhan** [comment]
Can you provide a complete example that runs on intellij? your read  me not show how to instrument coroutines.

**Comment by offbynull** [comment]
Yes it does. It sounds like you're new to Java and you don't know about
java agents or any of the build systems.

You need to become more familiar with the java ecosystem before moving
forward. I can't help you with this.


On Jan 17, 2018 8:26 PM, "fattyhan" <notifications@github.com> wrote:

Can you provide a complete example that runs on intellij? your read me not
show how to instrument coroutines.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/offbynull/coroutines/issues/78#issuecomment-358534156>,
or mute the thread
