### ISSUE TITLE
serialize a coroutine called inside a native method

### ISSUE THREAD

**Issue by publicocean0** [offbynull/coroutines#79]
Consider 2 different scenarios: 
1) first scenario
```
public static final class MyCoroutine implements Coroutine {
    @Override
    public void run(Continuation c) {
        execute_native_method();
       c.suspend();
    }
}
```
it is working ?
2) scenario 

```
public static final class MyCoroutine implements Coroutine {
 
  
    @Override
    public void run(Continuation c) {
       native_func(c, new NativeCallback(){  // inside JNI native_func    c.suspend() is executed before to call callback.

     public static void callback(){
           MyCoroutine.this.execute();
    }
      
    
   });
}

}

```
it is working? The status can be saved and restored also inside JNI?

**Comment by offbynull** [comment]
It won't work. If you want to suspend and continue inside of native code
(c++), I think boost has a coroutines module you can use. You can use this
package for the java portion and boost for the native portion.

**Comment by publicocean0** [comment]
i already tried to use boost but JVM crashs when i call java callback from inside a boost fiber.

**Comment by offbynull** [comment]
You'll need to discuss that with the folks who maintain boost.

**Comment by publicocean0** [comment]
I already done :) ahaha No solution if jvm dont work in this context

**Comment by publicocean0** [comment]
Sorry just last question . do you think in java is not possible because your library cant or because there is a therotical reason makking it impossible?

**Comment by offbynull** [comment]
There are special properties with JVM bytecode that make suspension and
continuation possible. C++ doesn't have those same properties, partly
because your code doesn't compile down to JVM bytecode. If it did, you
would very likely be able to use this package + you wouldn't have to use
JNI.

I actually don't know what kind of magic boost does under the hood to make
coroutines work, but I suspect that it's architecture specific.

On Jan 19, 2018 11:07 AM, "publicocean0" <notifications@github.com> wrote:

Sorry just last question . do you think in java is not possible because
your library cant or because there is a therotical reason makking it
impossible?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/offbynull/coroutines/issues/79#issuecomment-359060203>,
or mute the thread

**Comment by publicocean0** [comment]
I think i solved the problem using a coroutine in java  and a corotuine in c++. Pratically a pipeline of corotuines but in 2 distinct  and isolated words.
