### ISSUE TITLE
Bulk instrumentation of entire packages?

### ISSUE THREAD

**Issue by ivanr** [offbynull/coroutines#90]
Hi. I am investigating building a framework for collaborative processing based on your library. For example, the framework could offer a method to create a network connection, which would be blocking from the user code perspective, but which would (behind the scenes) initiate an async operation and suspend the coroutine. It would later resume the coroutine when the async operation completes.

The catch is that I want to do it without the user code being aware of the continuations. In other words, I'd like to abstract the concurrency model and keep it at the framework level. Basically, I want to stash the Continuation instance (or some other object) in a thread-local variable and use it from within the framework only.

As I understand it, the current implementation is that instrumentation is applied to all methods that accept Continuation. Would it instead be possible to have an option to apply instrumentation to all classes and methods in a package? Or, another option would be to trace all method invocation chains to find all possible paths that end with methods that touch Continuation instances and instrument only those chains.

I am not asking you to implement any of this, but I would appreciate hearing your opinion on whether this is feasible. And, if it is, some pointers would be helpful. Thanks.

**Comment by offbynull** [comment]
Project loom (continuations/coroutines officially supported on the JVM) is coming. This library is going to be obsolete. I would encourage you to focus your efforts on project loom instead.

**Comment by ivanr** [comment]
Thanks for your quick response. I am aware of project Loom, but playing with coroutines [now] is fun :)

**Comment by offbynull** [comment]
I'll be honest with you: this tool has outlived its usefulness for me and I have no time or interest in further maintaining it. What you're looking for may be possible with a competing tool called tascalate-javaflow, but last I checked it was much slower due to certain design decisions it made.

If you're dead set on using my package, it'll be up to you to make any necessary changes. Having said that, there's no guarantee any PR submission will be accepted / new release pushed out to maven central. In addition, the code has a steep learning curve because of all the different optimizations in place. 

I'm sorry.

**Comment by ivanr** [comment]
No worries. Thanks for the pointers. All the best.
